// Generated by https://quicktype.io

export interface UserVotesResponse {
  results: Results;
}

export interface Results {
  count: number;
  totalPages: number;
  CurrentPage: number;
  results: Vote[];
}

export interface Vote {
  publication_id: string;
  profile_id: string;
  created_at: string;
  updated_at: string;
  Publication: Publication;
}

export interface Publication {
  id: string;
  profile_id: string;
  title: string;
  description: string;
  content: string;
  picture: string;
  image_url: string;
  created_at: string;
  updated_at: string;
  City: City;
  publication_type_id: PublicationTypeID;
  tags: Tag[];
}

export interface City {
  id: string;
  name: string;
  State: State;
}

export interface State {
  id: string;
  name: string;
  Country: Tag;
}

export interface Tag {
  id: string;
  name: string;
}

export interface PublicationTypeID {
  id: string;
  name: string;
  description: string;
}

// Click on vote button

export interface VoteButton {
  publication_id: string;
  profile_id: string;
  created_at: string;
  updated_at: string;
}
